### ISSUE TITLE
네트워크 주제

### ISSUE THREAD

**Issue by Hamill210** [java-squid/lets-cs#2]
각자 하고 싶은 주제 2개를 올려주세요

**Comment by 102092** [comment]
1. 주소창에 특정 URL 값을 입력시키면 어떤 일이 일어나는가?
2. HTTP/HTTPS의 차이점을 설명하시오
3. TCP 3way handshake 에 대해 아는 대로 설명하시오
4. round robin에 대해서 설명하시오

**Comment by 102092** [comment]
1. HTTP 1.1 vs HTTP 2.0
2. Cookie vs Session

**Comment by Hamill210** [comment]
1. 네트워크 캐시
2. 로컬스토리지

**Comment by choichoigang** [comment]
1. SSL 클라이언트 인증 수순
2. HTTP 상태 코드

**Comment by Hamill210** [comment]
1. GET, POST 의 차이점

**Comment by 102092** [comment]
0608
- CSRF, XSS가 무엇이고 차이점을 설명
- 프록시 서버 vs 게이트웨이란? 사용하는 이유
- 프록시,게이트웨이,터널 이해와 활용
- webSocket의 기능과 동작 방식
